#!/bin/bash
#
# 00-welcome-header - create a greeting header for the MOTD
# Copyright (C) 2019 - 2020 Alexandre Popov <amocedonian@gmail.com>.
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

DESCRIPTION=$(lsb_release -d | awk 'FNR == 1 {print $2, $3, $4}')
CODE_NAME=$(lsb_release -c | awk '{print $2}')
KERNEL_INFO=$(uname -sr)

echo -e "Welcome to ${DESCRIPTION} \033[01;37m${CODE_NAME}\033[00m (${KERNEL_INFO})\n"
