#!/bin/sh
set -e

# grub-mkconfig helper script.
# Copyright (C) 2019 - 2020  Alexandre Popov <amocedonian@gmail.com>
#
# GRUB is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# GRUB is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GRUB.  If not, see <http://www.gnu.org/licenses/>.

# Include the GRUB helper library for grub-mkconfig.
. /usr/share/grub/grub-mkconfig_lib

set_mono_theme(){

  cat << EOF
set menu_color_normal=white/black
set menu_color_highlight=white/light-gray
EOF

}

set_mono_theme
