#!/bin/bash
#
# 20-connect-info - connection information for the MOTD
#
# Copyright (C) 2019 - 2020 Alexandre Popov <consiorp@gmail.com>.
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.

LINE_PREFIX="   "
DATE=$(date)

#wired_connect()
#{
#	local WIRED_STATE=$(ip a | awk 'FNR == 7 {print $9}')
#	local WIRED_IFACE=$()
#	Here you can add variables.
#
#	Here you can display connection information
#	if [ "$WIRED_STATE" = UP ]; then
#		echo -e "${LINE_PREFIX}Connection information on as of ${DATE}\n"
#
#	else
#		echo "${LINE_PREFIX}There is no internet connection. Perhaps the interface is not connected."
#		echo -e "${LINE_PREFIX}To connect it, please  enter the command: ${WIRED_IFACE}\n"
#	fi
#}

wireless_connect()
{
	local WIRELESS_STATE=$(ip a | awk 'FNR == 9 {print $9}')
	local WIRELESS_IFACE=$(iw dev | awk 'FNR == 2 {print $2}')
	local ACCESS_POINT=$(iwconfig ${WIRELESS_IFACE} | awk 'FNR == 2 {print $6}')
	local SSID=$(iw ${WIRELESS_IFACE} link | awk 'FNR == 2 {print $1, $2}')
	local RX=$(iw ${WIRELESS_IFACE} link | awk 'FNR == 4 {print $1, $2, $3}')
	local TX=$(iw ${WIRELESS_IFACE} link | awk 'FNR == 5 {print $1, $2, $3}')
	local SIGNAL_LEVEL=$(iw ${WIRELESS_IFACE} link | awk 'FNR == 6 {print $2, $3}')
	local TX_BITE_RATE=$(iw ${WIRELESS_IFACE} link | awk 'FNR == 7 {print $3, $4}')

if [ "$WIRELESS_STATE" = UP ]; then
    echo -e "${LINE_PREFIX}Connection information on as of ${DATE}\n"
    echo -e "${LINE_PREFIX}Access Point: ${ACCESS_POINT}\t${SSID}"
    echo -e "${LINE_PREFIX}${RX}\t\t\t${TX}"
    echo -e "${LINE_PREFIX}Signal level: ${SIGNAL_LEVEL}\t\tTX Bite Rate: ${TX_BITE_RATE}\n"
else
    echo "${LINE_PREFIX}There is no internet connection. Perhaps the interface is not connected."
    echo -e "${LINE_PREFIX}To connect it, please  enter the command: nmcli device connect ${WIRELESS_IFACE}.\n"
fi
}

wireless_connect
