#!/usr/bin/env bash
#
# mare - tool the home computer setup
# Copyright (C) 2020 Alexandre Popov <amocedonian@gmail.com>.
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

COMMAND="$1"

# Usage
while [ "$#" -gt 0 ]; do
	case "$1" in
		-m --menu )
		/usr/share/mare/menu.sh
		;;
		-h | --help )
		cat /usr/share/mare/data/usage.list
		exit 0 
		;;
		-v | --version )
		cat /usr/share/mare/data/release.list
		exit 0 
		;;
		* )
		echo "`basename $0:` wrong key — «$1»."
		echo "On command «mare --help» one can get additional information."
		exit 1
    	;;
    esac
	break
done

if [ -z "$COMMAND" ]; then
	echo "`basename $0:` indicate required action."
	echo "For help using the program, enter the command:"
	echo "mare -h or mare --help."
	exit 1
fi
shift
